apiVersion: v1
kind: Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  containers:
  - name: flask
    image: sharara99/flask-app-pipeline:3
    ports:
    - containerPort: 5000
